# Generated by Django 5.2.3 on 2025-07-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('total_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VegetableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(max_length=100)),
                ('veg_price', models.FloatField()),
                ('veg_kg', models.FloatField()),
                ('amount', models.FloatField()),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetables', to='app.customerorder')),
            ],
        ),
    ]
