# Generated by Django 5.2.3 on 2025-07-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customerorder_vegetableitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_name', models.CharField(max_length=100)),
                ('Number', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
