# Generated by Django 5.2.3 on 2025-07-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='Cus_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
