# Generated by Django 5.2.3 on 2025-07-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dash_cus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='Number',
            field=models.CharField(max_length=15),
        ),
    ]
